### ISSUE TITLE
First (standard) scene not visible?

### ISSUE THREAD

**Issue by shakerCH** [lociii/homeassistant-digitalstrom#5]
Hi
First - thanks a lot for this extension!
I have Digitalstrom at home and am playing around with it in Home Assistant. Could it be that the first (i.e. standard) scene of each room is missing?
As an example, I have a room called "small room" with the following settings:
- Scene 1: Night
- Scene 2: Full
- Scene 3: Night2
- Scene 4: -
![image](https://user-images.githubusercontent.com/59373601/77236850-a0926e80-6bc2-11ea-9af6-37368dd5fcdb.png)

I would expect to see scenes 1 to 3 (not 4 though as it doesn't have a name). However, in Home Assistant, I only see "Full" and "Night2":
![image](https://user-images.githubusercontent.com/59373601/77236901-27dfe200-6bc3-11ea-92fd-81ecd7082da5.png)

Any idea what I'm doing wrong?

**Comment by shakerCH** [comment]
Sorry, also to add: Using the developer tools, the only scene I see for that room is "Night2":
![image](https://user-images.githubusercontent.com/59373601/77237149-eac91f00-6bc5-11ea-8762-df3702c58454.png)

**Comment by lociii** [comment]
Hey @shakerCH,

thanks for the report. The basic concept of this integration is to use area scenes (Bereichsszenen).
See [info](https://github.com/lociii/homeassistant-digitalstrom/blob/master/info.md).
As digitalstrom distinguishes in naming between turn on and turn off scenes, this integration will always use the [name of the turn off scene](https://github.com/lociii/homeassistant-digitalstrom/blob/master/custom_components/digitalstrom/light.py#L133) as it comes first in numerical order. 

This is also why your first scene is not listed as it is the broadcast scene and the off broadcast (Aus) does not have a name assigned. Therefore the [underlying library will skip that scene](https://github.com/lociii/pydigitalstrom/blob/master/pydigitalstrom/client.py#L90).

As you are only the third user (including me) of this integration that I am aware of, please feel free to extend the documentation.
I'm currently working on the two open tickets listed in this project to make the integration more usable.

Best, Jens

**Comment by lociii** [comment]
Will close this soon as the original author is not replying and this is intended behavior.

**Comment by shakerCH** [comment]
Hi

Thanks a lot for explaining it (again). I played around with scene names and indeed, they do show up as described by you. I'll close this issue as it's just a simple misunderstanding from my side.

Wish you a good week!
Simon

**Comment by lociii** [comment]
Great that you got it working. Have fun and let me know if you have any other issues!
